# Generated by Django 2.2.4 on 2019-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('employee_code', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'EmployeeManagement',
            },
        ),
    ]
