# Generated by Django 2.2.4 on 2019-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='email_id',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
