# Generated by Django 2.2.4 on 2019-11-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanagement', '0002_auto_20191111_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagement',
            name='salary',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
